### ISSUE TITLE
B.I.O. 2021 Q1c cannot be realistically computed.

### ISSUE THREAD

**Issue by NobleOMD** [Spookiel/British-Informatics-Olympiad-Solutions#1]
Hi, been working on this question for a while now, have gotten to the point at which I'm looking for solutions. Your code for B.I.O. 2021 Q1c will get to the solution but my computer probably won't calculate it until the heat death of the universe. Is there something I am missing or just more power?

**Comment by teymour-aldridge** [comment]
It's definitely infeasible (the algorithm generates all 25! possibilities, which is something in the range of 10^25 possible permutations, and checks each one in turn).

In #2 I've suggested an alternative approach.

**Comment by NobleOMD** [comment]
Ty, your explanation was really helpful I think I need to learn binary trees properly and also dynamic programming a bit better. I am going to look through the lecture PowerPoint you referenced but what would you suggest to learn binary trees better?
