### ISSUE TITLE
2003 Q2, waves

### ISSUE THREAD

**Issue by ron0studios** [Spookiel/British-Informatics-Olympiad-Solutions#4]
Hello there! 
Firstly, I'd like to thank you for this repository, it is, as far as I've seen, the most complete resource for BIO answers I have come across. 
However, quite a few of the tricky question 2's have been left out, namely "waves", which is an implementation question in the 2003 BIO. 
I have been struggling to find a good implementation for this problem. If you have already completed this problem, please may you add it to the repository and if not, could you please provide any tips as for an implementation to this problem, I'd love to provide a pull request! 
thanks,

**Comment by ron0studios** [comment]
oh yes also I'd like to ask what the license for the repository is. is it MIT?

**Comment by Spookiel** [comment]
License is MIT, will add that asap. I can work on Waves if you’d like.

**Comment by ron0studios** [comment]
> License is MIT, will add that asap. I can work on Waves if you’d like.

I'm working on a c++ solution for waves, I will contribute this as soon as I can 👍🏽
