### ISSUE TITLE
2003 Q3 

### ISSUE THREAD

**Issue by ron0studios** [Spookiel/British-Informatics-Olympiad-Solutions#5]
could you please explain this question a bit more please? For example, I don't get why creating the table of N length helps to solve the problem in the first place. Thanks!

**Comment by Spookiel** [comment]
Would you still like me to explain this?

**Comment by Spookiel** [comment]
I decided to show how the bottom-up DP would be done at the start so it fitted with the editorial better and could translate to languages where there is no LRU-cache.
